num = ["ZERO","ONE","TWO","THREE","FOUR","FIVE","SIX","SEVEN","EIGHT","NINE","TEN","ELEVEN","TWELVE","THIRTEEN","FOURTEEN","FIFTEEN","SIXTEEN","SEVENTEEN"
       ,"EIGHTEEN","NINTEEN"]

a = int(input("ENTER NUMBER:"))

print(num[a])